name: Update Portfolio JSON every day

on:
  schedule:
    - cron: "30 5 * * *" 
  workflow_dispatch: # manual trigger

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.18"

      - name: Install dependencies
        run: pip install requests tzdata

      - name: Run JSON update script
        run: python update_portfolio.py

      - name: Commit and push changes if needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # Only commit if there are changes
          if ! git diff --quiet; then
            git add projects_data.json
            git commit -m "🔄 Portfolio data updated"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main

            # Purge jsDelivr cache for this file
            curl -X GET "https://purge.jsdelivr.net/gh/smriti2805/githubInfoJson@latest/projects_data.json"
          else
            echo "No changes in JSON — skipping commit & purge."
          fi
